[package]
name = "lama"
version = "0.1.0"
description = "Learning And Manipulation of Automata"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
automata = { version = "0.2", path = "../automata" }
automata-learning = { version = "0.1", path = "../automata-learning" }
clap = { version = "4.4", features = ["cargo"] }
tracing = "0.1"
tracing-subscriber = "0.3"
