[package]
name = "lama"
version = "0.1.0"
description = "Learning And Manipulation of Automata"

[workspace]
members = ["automata", "bin"]


[[bin]]
name = "lama"
path = "bin/src/main.rs"
test = false
doctest = false
