#!/usr/bin/env bash
set -e

cargo fmt --check --all
echo "cargo fmt --check --all passed"
cargo clippy --workspace -- -D warnings
echo "cargo clippy --all -- -D warnings passed"
cargo doc --workspace --no-deps 
cargo test --all
echo "cargo test --all passed"
