name: Run checks

on:
  pull_request:
    branches:
      - '*'
      - '!main'
        
jobs:
  linttest:
    name: Run checks and lints
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
      - name: Verify correct formatting
        run: cargo fmt --all --check
      - name: Ensure that clippy is happy
        run: cargo clippy --workspace --all-targets -- -D warnings
      - name: Run all tests and see that there are no regressions
        run: cargo test --all
