name: Verify code

on:
  pull_request:
    branches:
      - '*'
      - '!main'
        
jobs:
  check:
    name: Run checks and lints
    strategy:
      matrix:
        platform:
          - os_name: Linux-x86_64
            os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu

          - os_name: Windows-aarch64
            os: windows-latest
            target: aarch64-pc-windows-msvc

          - os_name: macOS-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin

    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform.target }}
      - uses: Swatinem/rust-cache@v2
      - name: Verify correct formatting
        run: cargo fmt --all --check
      - name: Ensure that clippy is happy
        run: cargo clippy --workspace --all-targets -- -D warnings
      - name: Compile
        run: cargo build --locked --target ${{ matrix.platform.target }}
      - name: Run all tests and see that there are no regressions
        run: cargo test --all
